### ISSUE TITLE
run down2slc_sen.py error

### ISSUE THREAD

**Issue by chenweicug** [ymcmrs/PyINT#2]
down2slc_sen.py pyint 20191124
Traceback (most recent call last):
  File "/home/chen/Software/InSAR/PyINT/pyint/down2slc_sen.py", line 154, in <module>
    main(sys.argv[:])    
  File "/home/chen/Software/InSAR/PyINT/pyint/down2slc_sen.py", line 113, in main
    raw_files = ut.read_txt2list(t_date)
  File "/home/chen/Software/InSAR/PyINT/pyint/_utils.py", line 187, in read_txt2list
    if isinstance(A[0],bytes):
IndexError: too many indices for array

**Comment by ymcmrs** [comment]
should be fixed now
