### ISSUE TITLE
bugs in extract_s1_bursts.py

### ISSUE THREAD

**Issue by chenweicug** [ymcmrs/PyINT#3]
Hi,
      When i set the  start_swath and end_swath is not 1 and 3, the extract_s1_bursts.py script will give the following error:
     
extract_s1_bursts.py xietongmenT128F89S1A 20181228
Traceback (most recent call last):
  File "/home/chen/Software/InSAR/PyINT/pyint/extract_s1_bursts.py", line 287, in <module>
    main(sys.argv[:])
  File "/home/chen/Software/InSAR/PyINT/pyint/extract_s1_bursts.py", line 242, in main
    SB1=int(AA[ii-1,0])
IndexError: too many indices for array
the script seem to work well when   use the whole swath in sentinel1

**Comment by ymcmrs** [comment]
In the latest version of PyINT, which will be updated later, this script is not used.

The basic idea behind this script is: 1) determine the common bursts, e.g., 1-9, 2-10,; 2) extract the related bursts. While, this is not necessary for the new version of GAMMA.
